---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
airlines_raw <- read_csv("data/airlines.csv")
airports_raw <- read_csv("data/airports.csv")
flights_raw <- read_csv("data/flights.csv")
planes_raw <- read_csv("data/planes.csv")
weather_raw <- read_csv("data/weather.csv")
```

```{r}
weather_raw %>%
  filter(origin == "EWR") %>% 
  summarise(across(.cols = everything(),
                   .fns = ~sum(!is.na(.x))/8735*100))
```

```{r}
weather_raw %>% 
  ggplot(aes(x = wind_speed, y = wind_gust)) +
  geom_point()
```

```{r}
flights_raw %>% 
  filter(origin == "EWR") %>% 
  dim()
```

```{r}
flights_raw %>% 
  filter(origin == "EWR") %>%
  group_by(year, month, day) %>% 
  count()
```

```{r}
airports_raw %>% 
  summarise(across(.cols = everything(),
                   .fns = ~sum(is.na(.x))))
```

```{r}
flights_raw %>% 
  summarise(across(.cols = everything(),
                   .fns = ~sum(is.na(.x))))
```

```{r}
planes_raw %>% 
  summarise(across(.cols = everything(),
                   .fns = ~sum(is.na(.x))))
```

```{r}
flights_raw %>% 
  filter(dest == "EWR")
```

--------------------------------------------------------------------------------

# CLEANING

```{r}
airlines <- airlines_raw %>% 
  rename("airline_name" = "name")
```

```{r}
airports <- airports_raw %>% 
  select(faa, name) %>% 
  rename("airport_name" = "name")
```

"The Federal Aviation Administration (FAA) considers a flight to be delayed when 
it is 15 minutes later than its scheduled time."

```{r}
flights <- flights_raw %>%
  mutate(hour = if_else(hour == 1, 24, hour)) %>%
  select(month, day, hour, dep_delay, carrier, flight, 
         tailnum, origin, distance, time_hour) %>% 
  drop_na() %>% 
  arrange(month) %>% 
  mutate(delayed = if_else(dep_delay >= 15, TRUE, FALSE),
         weekday = weekdays(time_hour),
         month = lubridate::month(month, label = TRUE, abbr = FALSE))
```

```{r}
flights_EWR <- flights %>% 
  filter(origin == "EWR") %>% 
  select(-origin)
```

```{r}
planes <- planes_raw %>% 
  select(-speed)
```

```{r}
weather <- weather_raw %>% 
  select(-year, -month, -day, -hour) %>% 
  mutate(wind_dir = case_when(
    wind_dir %in% c(350, 360, 0, 10) ~ "N",
    wind_dir %in% c(20, 30) ~ "N/NE",
    wind_dir %in% c(40, 50) ~ "NE",
    wind_dir %in% c(60, 70) ~ "E/NE",
    wind_dir %in% c(80, 90, 100) ~ "E",
    wind_dir %in% c(110, 120) ~ "E/SE",
    wind_dir %in% c(130, 140) ~ "SE",
    wind_dir %in% c(150, 160) ~ "S/SE",
    wind_dir %in% c(170, 180, 190) ~ "S",
    wind_dir %in% c(200, 210) ~ "S/SW",
    wind_dir %in% c(220, 230) ~ "SW",
    wind_dir %in% c(240, 250) ~ "W/SW",
    wind_dir %in% c(260, 270, 280) ~ "W",
    wind_dir %in% c(290, 300) ~ "W/NW",
    wind_dir %in% c(310, 320) ~ "NW",
    wind_dir %in% c(330, 340) ~ "N/NW",
  ))
```

```{r}
weather_EWR <- weather %>% 
  filter(origin == "EWR") %>% 
  select(-origin)
```

--------------------------------------------------------------------------------

# Joining 

```{r}
all <- flights %>% 
  left_join(airlines, by = "carrier") %>% 
  left_join(airports, by = c("origin" = "faa")) %>% 
  left_join(weather, by = c("time_hour", "origin")) %>% 
  left_join(planes, by = "tailnum")
```

```{r}
all_EWR <- flights_EWR %>% 
  left_join(airlines, by = "carrier") %>% 
  left_join(weather_EWR, by = "time_hour") %>% 
  left_join(planes, by = "tailnum")
```

--------------------------------------------------------------------------------

```{r}
write_csv(all_EWR, "clean_data/all_EWR.csv")
write_csv(all, "clean_data/all.csv")
```

