---
title: "EDA"
output: html_notebook
---

```{r}
library(tidyverse)
library(extrafont)
```

```{r}
all_EWR <- read_csv("clean_data/all_EWR.csv")
all <- read_csv("clean_data/all.csv")
```


# GENERAL DELAYS ANALYSIS

```{r}
all_EWR %>% 
  group_by(delayed) %>% 
  summarise(n = n()) %>% 
  mutate(percent = n/sum(n)*100)
```

```{r}
all_EWR %>% 
  ggplot(aes(x = delayed)) +
  geom_bar()
```

```{r}
all_EWR %>% 
  filter(dep_delay >= 15) %>% 
  ggplot(aes(x = dep_delay)) +
  geom_histogram()
```

```{r}
all_EWR %>% 
  filter(delayed == TRUE) %>% 
  mutate(delay_period = case_when(
    dep_delay < 10 ~ "< 10min",
    dep_delay <= 60 ~ "10min - 60min",
    dep_delay > 60 ~ "> 60min"
  )) %>% 
  group_by(delay_period) %>% 
  summarise(n = n()) %>% 
  mutate(percentage = n / sum(n))
```

```{r}
month_plot_text <- all_EWR %>% 
  group_by(month, delayed) %>% 
  summarise(n = n()) %>% 
  mutate(delay_percent = round(n / sum(n) * 100)) %>% 
  filter(delayed == TRUE)
```

```{r}
all_EWR %>%
  ggplot(aes(x = fct_inorder(month), fill = delayed)) +
  geom_bar(position = "fill") +
  geom_text(aes(y = delay_percent/100 - 0.03, 
                label = str_c(delay_percent, "%")), 
            data = month_plot_text)
```

```{r}
hour_plot_text <- all_EWR %>%
  group_by(hour, delayed) %>% 
  summarise(n = n()) %>% 
  mutate(delay_percent = round(n / sum(n) * 100)) %>% 
  filter(delayed == TRUE)
```

```{r}
all_EWR %>%
  ggplot(aes(x = hour, fill = delayed)) +
  geom_bar(position = "fill") +
  geom_text(aes(y = delay_percent/100 - 0.03, 
                label = str_c(delay_percent, "%")), 
            data = hour_plot_text,
            size = 3)
```

```{r}
all_EWR %>% 
  ggplot(aes(x = weekday, fill = delayed)) +
  geom_bar(position = "fill")
```

```{r}
flights_by_day <- all_EWR %>% 
  group_by(month, day) %>% 
  summarise(percentage_delays = sum(delayed) / n() * 100,
            total_flights = n())

flights_by_day %>% 
  ggplot(aes(x = total_flights, y = percentage_delays)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
all_EWR %>% 
  ggplot(aes(x = carrier, fill = delayed)) +
  geom_bar(position = "fill")

all_EWR %>% 
filter(delayed == TRUE) %>% 
  mutate(delay_period = case_when(
    dep_delay < 10 ~ "< 10min",
    dep_delay <= 60 ~ "10min - 60min",
    dep_delay > 60 ~ "> 60min"
  )) %>%
  ggplot(aes(x = carrier, fill = delay_period)) +
  geom_bar(position = "fill")
```

```{r}
all_EWR %>% 
  ggplot(aes(x = delayed, y = distance)) +
  geom_boxplot()
```

--------------------------------------------------------------------------------


# PLANE

```{r}
all_EWR %>% 
  drop_na(year) %>% 
  filter(year != 0) %>% 
  ggplot(aes(x = delayed, y = year)) +
  geom_boxplot()
```

```{r}
all_EWR %>% 
  drop_na(manufacturer) %>% 
  ggplot(aes(x = manufacturer, fill = delayed)) +
  geom_bar() +
  coord_flip()

all_EWR %>% 
  drop_na(manufacturer) %>% 
  ggplot(aes(x = manufacturer, fill = delayed)) +
  geom_bar(position = "fill") +
  coord_flip()
```

--------------------------------------------------------------------------------

# WEATHER

```{r}
all_EWR %>% 
  drop_na(temp) %>%
  ggplot(aes(x = delayed, y = temp)) +
  geom_boxplot()

all_EWR %>% 
  drop_na(dewp) %>%
  ggplot(aes(x = delayed, y = dewp)) +
  geom_boxplot()

all_EWR %>% 
  drop_na(humid) %>%
  ggplot(aes(x = delayed, y = humid)) +
  geom_boxplot()

all_EWR %>% 
  drop_na(precip) %>%
  ggplot(aes(x = delayed, y = precip)) +
  geom_boxplot()

all_EWR %>% 
  drop_na(pressure) %>%
  ggplot(aes(x = delayed, y = pressure)) +
  geom_boxplot()
```

```{r}
all_EWR %>% 
  drop_na(wind_dir) %>% 
  ggplot(aes(x = wind_dir, fill = delayed)) +
  geom_bar(position = "fill")
```

```{r}
all %>% 
  drop_na(wind_speed) %>%
  ggplot(aes(x = delayed, y = wind_speed)) +
  geom_boxplot()

all %>% 
  drop_na(wind_speed) %>%
  ggplot(aes(x = wind_speed, y = dep_delay)) +
  geom_point()

all_EWR %>% 
  drop_na(wind_gust) %>%
  ggplot(aes(x = delayed, y = wind_gust)) +
  geom_boxplot()

all %>% 
  mutate(delayed = if_else(dep_delay > 15, TRUE, FALSE)) %>% 
  drop_na(wind_gust) %>%
  ggplot(aes(x = as.factor(wind_gust), fill = delayed)) +
  geom_bar(position = "fill")
```

```{r}
all_EWR %>% 
  drop_na(visib) %>%
  ggplot(aes(x = delayed, y = visib)) +
  geom_boxplot()

all %>% 
  drop_na(visib) %>%
  ggplot(aes(x = visib, y = dep_delay)) +
  geom_point()

all_EWR %>% 
  drop_na(visib) %>%
  ggplot(aes(x = as.factor(visib), fill = delayed)) +
  geom_bar(position = "fill")

all_EWR %>% 
  drop_na(visib) %>%
  filter(delayed == TRUE) %>% 
  mutate(delay_period = case_when(
    dep_delay < 10 ~ "< 10min",
    dep_delay <= 60 ~ "10min - 60min",
    dep_delay > 60 ~ "> 60min"
  )) %>%
  ggplot(aes(x = as.factor(visib), fill = delay_period)) +
  geom_bar(position = "fill")
```

```{r}
all_EWR %>% 
  drop_na(visib) %>% 
  mutate(visib_less_10 = if_else(visib < 10, TRUE, FALSE)) %>% 
  group_by(visib_less_10) %>% 
  summarise(n = n()) %>% 
  mutate(n/sum(n))
```

```{r}
all_EWR %>% 
  drop_na(visib) %>%
  mutate(visib_less_2 = if_else(visib < 2, TRUE, FALSE)) %>% 
  group_by(visib_less_2) %>% 
  summarise(n = n()) %>% 
  mutate(n/sum(n))
```

```{r}
all_EWR %>% 
  filter(visib < 1) %>% 
  arrange(visib) %>% 
  select(dep_delay, delayed, visib, engines)
```

--------------------------------------------------------------------------------

# PLOTS FOR SLIDES

```{r}
percent_delayed <- all_EWR %>% 
  group_by(delayed) %>% 
  summarise(n = n()) %>% 
  mutate(percent = round(n/sum(n)*100, digits = 2))
```

```{r}
percent_delayed %>% 
  ggplot(aes(x = delayed, y = percent)) +
  geom_col(fill = "#55747e", width = 0.7) + 
  geom_hline(yintercept = 0, color = "black", size = 0.8) +
  geom_text(aes(y = percent, label = str_c(percent, "%")), 
            data = percent_delayed, nudge_y = -5, 
            size = 6, colour = "white") +
  scale_x_discrete(labels = c("On Time", "Delayed")) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 12, colour = "black"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey80"),
        panel.background = element_rect(fill = "#ecfafd"),
        plot.background = element_rect(fill = "#ecfafd"))
#ggsave("delay_percentage.png")
```

```{r}
all_EWR %>%
  group_by(hour, delayed) %>% 
  summarise(n = n()) %>% 
  mutate(delay_percent = n / sum(n)) %>% 
  filter(delayed == TRUE) %>% 
  ggplot(aes(x = hour, y = delay_percent)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
                     labels = scales::percent) +
  scale_x_continuous(breaks = c(5:24)) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(colour = "#6A838B"),
        panel.background = element_rect(fill = "#55747e"),
        plot.background = element_rect(fill = "#55747e")) +
  theme(axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 10, colour = "white"))
#ggsave("hourly_delay_percentage.png")
```