---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(pROC)
library(glmulti)
library(ggfortify)
library(janitor)
library(pROC)
library(modelr)
library(ranger)
library(randomForest)
library(caret)
```

```{r}
all_EWR <- read_csv("clean_data/all_EWR.csv")
```

```{r}
all_EWR_log <- all_EWR %>% 
  select(month, weekday, hour, carrier, delayed, wind_dir, wind_speed, 
         wind_gust, visib, year, manufacturer) %>% 
  drop_na() %>% 
  mutate(month = factor(month, ordered = FALSE)) %>% 
  mutate(across(c(weekday, carrier, wind_dir, manufacturer), 
                ~as.factor(.x)))
```

```{r}
alias(delayed ~ ., data = all_EWR_log)
```

```{r}
all_EWR_log <- all_EWR_log %>% 
  select(-wind_gust)
```

```{r}
GGally::ggpairs(all_EWR_log %>% select(-manufacturer))
```

--------------------------------------------------------------------------------

# LOGISTIC REGRESSION

```{r}
glmulti_search_all_mains <- glmulti(
  delayed ~ ., 
  data = all_EWR_log,
  level = 1,               # No interactions considered, main effects only
  method = "h", 
  crit = "bic",
  confsetsize = 10,
  plotty = F, 
  report = T,
  fitfunction = "glm",
  family = binomial(link = "logit"))
```

Best model: delayed~1+month+weekday+carrier+wind_dir+hour+wind_speed+visib

```{r}
glmulti_search_previous_mains_one_pair <- glmulti(
  delayed ~ month + weekday + carrier + wind_dir + hour + wind_speed + visib, 
  data = all_EWR_log,
  level = 2,               # Interactions considered
  method = "h",
  crit = "bic",
  confsetsize = 10, 
  marginality = TRUE,      # consider pairs only if both main effects in model
  minsize = 8,
  maxsize = 8,
  plotty = F, 
  report = T,
  fitfunction = "glm",
  family = binomial(link = "logit"))
```

Best model: delayed~1+month+weekday+carrier+hour+visib+weekday:month+carrier:hour

```{r}
mod_log <- glm(delayed ~ month + weekday + carrier + wind_dir + hour + 
                 wind_speed + visib,
               data = all_EWR_log, 
               family = binomial(link = "logit"))
```

```{r}
summary(mod_log)
```

```{r}
tibble(hour = 5, month = "August", weekday = "Monday", carrier = "AS", wind_dir = "N", wind_speed = 10, visib = 10) %>%
  modelr::add_predictions(mod_log, type='response') %>%
  mutate(odds = pred/(1-pred)) %>%
  select(odds)
```

```{r}
broom::tidy(mod_log) %>% 
  filter(term == "carrierB6") %>% 
  select(estimate) %>% 
  exp()
```

```{r}
log_mod_pred <- all_EWR_log %>% 
  add_predictions(mod_log, type = "response")
```

```{r}
roc_mod_log <- log_mod_pred %>% 
  roc(response = delayed, predictor = pred)
roc_mod_log %>% 
  ggroc() +
  coord_fixed()
```

```{r}
auc(roc_mod_log)
```

```{r}
caret::varImp(mod_log, scale = TRUE)
```

Best model: delayed~1+month+weekday+carrier+wind_dir+hour+wind_speed+visib

```{r}
log_mod_month <- glm(delayed ~ month,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_weekday <- glm(delayed ~ weekday,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_carrier <- glm(delayed ~ carrier,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_wind_dir <- glm(delayed ~ wind_dir,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_hour <- glm(delayed ~ hour,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_wind_speed <- glm(delayed ~ wind_speed,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
log_mod_visib <- glm(delayed ~ visib,
                     data = all_EWR_log, 
                     family = binomial(link = "logit"))
```

```{r}
roc_month <- all_EWR_log %>% 
  add_predictions(log_mod_month, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_weekday <- all_EWR_log %>% 
  add_predictions(log_mod_weekday, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_carrier <- all_EWR_log %>% 
  add_predictions(log_mod_carrier, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_wind_dir <- all_EWR_log %>% 
  add_predictions(log_mod_wind_dir, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_hour <- all_EWR_log %>% 
  add_predictions(log_mod_hour, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_wind_speed <- all_EWR_log %>% 
  add_predictions(log_mod_wind_speed, type = "response") %>% 
  roc(response = delayed, predictor = pred)
roc_visib <- all_EWR_log %>% 
  add_predictions(log_mod_visib, type = "response") %>% 
  roc(response = delayed, predictor = pred)
```

```{r}
ggroc(data = list(roc_month, roc_weekday, roc_carrier,
                  roc_wind_dir, roc_hour, roc_wind_speed, 
                  roc_visib)) +
  coord_fixed()
```

```{r}
for(x in list(roc_month, roc_weekday, roc_carrier,
                  roc_wind_dir, roc_hour, roc_wind_speed, 
                  roc_visib)){
  print(auc(x))
                  }
```

```{r}
all_EWR_log_scaled <- all_EWR_log %>% 
  mutate(across(.cols = where(is.numeric), .fns = ~scale(.x)))
```

```{r}
mod_log_norm <- glm(delayed ~ month + weekday + carrier + wind_dir + hour + 
                      wind_speed + visib,
                    data = all_EWR_log, 
                    family = binomial(link = "logit"))
```

```{r}
summary(mod_log_norm)
```

--------------------------------------------------------------------------------

# LINEAR REGRESSION

```{r}
all_EWR_lin <- all_EWR %>% 
  select(month, weekday, hour, dep_delay, carrier, wind_dir,
         wind_speed, visib, year, manufacturer) %>% 
  drop_na() %>% 
  mutate(month = factor(month, ordered = FALSE)) %>% 
  mutate(across(c(weekday, carrier, wind_dir, manufacturer), 
                ~as.factor(.x)))
```

```{r}
regsubsets_forward <- regsubsets(dep_delay ~ ., 
                                 data = all_EWR_lin,
                                 nvmax = 94,
                                 method = "forward")
```

```{r}
summary(regsubsets_forward)
```

```{r}
plot(regsubsets_forward, scale = "adjr2")
plot(regsubsets_forward, scale = "bic")
plot(summary(regsubsets_forward)$rsq, type = "b")
plot(summary(regsubsets_forward)$bic, type = "b")
```

```{r}
summary(regsubsets_forward)$which[15,]
```

```{r}
mod_1 <- lm(dep_delay ~ hour + wind_speed + visib, data = all_EWR_lin)
mod_month <- lm(dep_delay ~ hour + wind_speed + visib + month, 
                data = all_EWR_lin)
anova(mod_1, mod_month)
```

```{r}
mod_weekday <- lm(dep_delay ~ hour + wind_speed + visib + month + weekday, 
                data = all_EWR_lin)
anova(mod_month, mod_weekday)
```

```{r}
mod_carrier <- lm(dep_delay ~ hour + wind_speed + visib + 
                    month + weekday + carrier, 
                data = all_EWR_lin)
anova(mod_weekday, mod_carrier)
```

```{r}
mod_manufacturer <- lm(dep_delay ~ hour + wind_speed + visib + 
                    month + weekday + carrier + manufacturer, 
                data = all_EWR_lin)
anova(mod_carrier, mod_manufacturer)
```

```{r}
mod_wind_dir <- lm(dep_delay ~ hour + wind_speed + visib + month + 
                     weekday + carrier + manufacturer + wind_dir, 
                data = all_EWR_lin)
anova(mod_manufacturer, mod_wind_dir)
```

```{r}
summary(mod_wind_dir)
```

```{r}
autoplot(mod_wind_dir)
```

--------------------------------------------------------------------------------

# RANDOM FOREST MODEL

```{r}
rf_classifier <- ranger(delayed ~ ., 
                        data = all_EWR_log,
                        importance = "impurity",
                        num.trees = 500,
                        mtry = 2,
                        min.node.size = 1)
rf_classifier
```

```{r}
ranger::importance(rf_classifier) %>% 
broom::tidy() %>% 
  arrange(desc(x)) %>% 
  ggplot(aes(x = x, y = reorder(names, x))) +
  geom_point()
```

--------------------------------------------------------------------------------

# PLOTS FOR SLIDES

```{r}
roc_mod_log %>% 
  ggroc(colour = "#55747e") +
  coord_fixed() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_line(colour = "white"),
        panel.background = element_rect(fill = "#c7d0d8"),
        plot.background = element_rect(fill = "#c7d0d8")) +
  theme(axis.ticks.y = element_blank(),
        axis.text = element_text(size = 10, colour = "grey10"))
#ggsave("ROC_curve.png")
```

```{r}
ranger::importance(rf_classifier) %>% 
broom::tidy() %>% 
  arrange(desc(x)) %>% 
  ggplot(aes(x = x, y = reorder(names, x))) +
  geom_point() +
  scale_x_continuous(limits = c(0, 5800),
                     breaks = seq(0, 6000, 1000)) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_line(colour = "white"),
        panel.background = element_rect(fill = "#c7d0d8"),
        plot.background = element_rect(fill = "#c7d0d8")) +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(size = 10, colour = "grey10"))
#ggsave("variable_importance.png")
```
