---
title: "Project Plan"
output: html_notebook
---

## Context

#### Business intelligence and data-driven decision making

Extracting key summaries, trends and insights from actual data and presenting
them in a clear and accessible way, will allow the business to make better 
informed, data-driven decisions.

#### Domain knowledge and the business context

The organisation is Newark Airport, based in New Jersey, USA. The Airport is
responsible for the safe departure and arrival of flights. My analysis will
examine the key factors that impact flight delays: this will
help the business to decide where to invest resources to improve the percentage
of departure delays, which is their primary goal.

## Data

#### Internal and external data sources

I used 5 datasets in total for this project. The largest dataset contained
303,748 rows. The data sources were all internal, as they were provided by 
Newark airport. 

#### Types of data

I worked with dates and times, as well as categorical and numerical data. 
I used continuous numerical variables, such as wind speed, as well as discrete 
numerical variables, such as the number of engines in a plane.
All of the categorical variables used were nominal. 

#### Data formats

All files were provided in a CSV format. 

#### Data quality and bias

The data provided was relevant and accurate. Most of the datasets had a very
small amount of missing values apart from weather.csv dataset, with the majority
of values missing.
The data also excluded records of cancellations, arrivals and international
flights.

The data contains complete records of domestic departures in a given period of 
time, and the nature of this prevents it from being susceptible to bias.

## Ethics

#### Ethical issues in data sourcing and extraction

The datasets do not contain any sensitive data, or in fact any data at all on 
individual people. It being purely a record of flights, planes and weather, I do
not have any ethical concerns with this data. 

#### Ethical implications of business requirements

I do not believe there will be any ethical implications as the business is
employing its own data to make improvements to their own facilities. This should
not have an impact on any individuals both within and outwith the organisation.


## Analysis

#### Stages in the data analysis process

The main stages in the data analysis process included:

- Cleaning and joining of the data
- Exploratory data analysis
- Data preparation for model building
- Model building for explanatory purposes
- Conclusions and recommendations

#### Tools for data analysis

The main tool that I used was R within RStudio.
The main packackes that I used included tidyverse, glmulti and ranger.

#### Descriptive, diagnostic, predictive and prescriptive analysis

My analysis falls under descriptive and diagnostic categories. This is because
the aims were to describe and summarise the nature of departure delays in 2017, 
as well as to help understand what factors caused these delays.